version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: windgo-chat-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: windgo_chat
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d windgo_chat"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: windgo-chat-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
