name: CI/CD on Self-Hosted Runner
on:
  push:
    branches:
      - dev 
      
env:
  PROJECT_DIR: ${{ vars.PROJECT_DIR }}

jobs:
  test:
    name: Test Code
    runs-on: self-hosted
    steps:
      - name: Checkout Source Code
        run: |
          set -e
          cd $PROJECT_DIR
          git fetch origin dev
          git reset --hard origin/dev

      - name: Setup Go Environment
        run: |
          set -e
          cd $PROJECT_DIR
          export PATH=$PATH:/usr/local/go/bin
          go mod tidy

      - name: Validate Code Structure (go vet)
        run: |
          set -e
          cd $PROJECT_DIR
          export PATH=$PATH:/usr/local/go/bin
          go vet ./...

      - name: Run Unit Tests
        run: |
          set -e
          cd $PROJECT_DIR
          export PATH=$PATH:/usr/local/go/bin
          go test ./...

  build:
    name: Build Binary
    runs-on: self-hosted
    needs: test 
    steps:
      - name: Build executable
        run: |
          set -e
          cd $PROJECT_DIR
          export PATH=$PATH:/usr/local/go/bin
          go build -o windgo-backend-new main.go

  deploy:
    name: Deploy Backend
    runs-on: self-hosted
    needs: build 
    steps:
      - name: Secure Deploy
        run: |
          sudo cp windgo-backend-new /opt/windgo/windgo-backend
          sudo chown nguyenhieu:nguyenhieu /opt/windgo/windgo-backend
          sudo chmod +x /opt/windgo/windgo-backend
          
          sudo fuser -k 8080/tcp || true
          
          sudo -u nguyenhieu bash -c "cd /opt/windgo; RUNNER_TRACKING_ID='' nohup ./windgo-backend > app.log 2>&1 &"
          sleep 3
          cat app.log
